package cascading.legstar.cobolcopybook.beans.bean7.bind;

import cascading.legstar.cobolcopybook.beans.bean7.Kcp01V05NationalInsuranNo1;
import cascading.legstar.cobolcopybook.beans.bean7.ObjectFactory;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.ICobolPackedDecimalBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * Kcp01V05NationalInsuranNo1.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class Kcp01V05NationalInsuranNo1Binding extends CComplexBinding
  {

  /**
   * Maximum host bytes size for this complex object.
   */
  private static final int BYTE_LENGTH = 7;
  /**
   * Binding factory.
   */
  private static final ICobolBindingFactory BF = CobolBindingFactory.getBindingFactory();
  /**
   * Static reference to Value object factory to be used as default.
   */
  private static final ObjectFactory JF = new ObjectFactory();
  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;
  /**
   * Logger.
   */
  private final Log _log = LogFactory.getLog( getClass() );
  /**
   * Child bound to value object property Kcp01V05NatinsNo1A(String).
   */
  public ICobolStringBinding _kcp01V05NatinsNo1A;
  /**
   * Child bound to value object property Kcp01V05NatinsNo1B(Integer).
   */
  public ICobolPackedDecimalBinding _kcp01V05NatinsNo1B;
  /**
   * Child bound to value object property Kcp01V05NatinsNo1C(String).
   */
  public ICobolStringBinding _kcp01V05NatinsNo1C;
  /**
   * Value object to which this cobol complex element is bound.
   */
  private Kcp01V05NationalInsuranNo1 mValueObject;
  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public Kcp01V05NationalInsuranNo1Binding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public Kcp01V05NationalInsuranNo1Binding( final Kcp01V05NationalInsuranNo1 valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public Kcp01V05NationalInsuranNo1Binding( final String bindingName, final String fieldName, final ICobolComplexBinding parentBinding, final Kcp01V05NationalInsuranNo1 valueObject )
    {

    super( bindingName, fieldName, Kcp01V05NationalInsuranNo1.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /**
   * Creates a binding property for each child.
   */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _kcp01V05NatinsNo1A = BF.createStringBinding( "Kcp01V05NatinsNo1A", "Kcp01V05NatinsNo1A", String.class, this );
    _kcp01V05NatinsNo1A.setCobolName( "KCP01V05-NATINS-NO-1A" );
    _kcp01V05NatinsNo1A.setByteLength( 2 );
    _kcp01V05NatinsNo1B = BF.createPackedDecimalBinding( "Kcp01V05NatinsNo1B", "Kcp01V05NatinsNo1B", Integer.class, this );
    _kcp01V05NatinsNo1B.setCobolName( "KCP01V05-NATINS-NO-1B" );
    _kcp01V05NatinsNo1B.setByteLength( 4 );
    _kcp01V05NatinsNo1B.setTotalDigits( 7 );
    _kcp01V05NatinsNo1B.setIsSigned( true );
    _kcp01V05NatinsNo1C = BF.createStringBinding( "Kcp01V05NatinsNo1C", "Kcp01V05NatinsNo1C", String.class, this );
    _kcp01V05NatinsNo1C.setCobolName( "KCP01V05-NATINS-NO-1C" );
    _kcp01V05NatinsNo1C.setByteLength( 1 );

        /* Add children to children list */
    getChildrenList().add( _kcp01V05NatinsNo1A );
    getChildrenList().add( _kcp01V05NatinsNo1B );
    getChildrenList().add( _kcp01V05NatinsNo1C );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createKcp01V05NationalInsuranNo1();
    }

  /**
   * {@inheritDoc}
   */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _kcp01V05NatinsNo1A */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp01V05NatinsNo1A" + " value=" + mValueObject.getKcp01V05NatinsNo1A() );
      }
    _kcp01V05NatinsNo1A.setObjectValue( mValueObject.getKcp01V05NatinsNo1A() );
        /* Get Value object property _kcp01V05NatinsNo1B */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp01V05NatinsNo1B" + " value=" + mValueObject.getKcp01V05NatinsNo1B() );
      }
    _kcp01V05NatinsNo1B.setObjectValue( mValueObject.getKcp01V05NatinsNo1B() );
        /* Get Value object property _kcp01V05NatinsNo1C */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp01V05NatinsNo1C" + " value=" + mValueObject.getKcp01V05NatinsNo1C() );
      }
    _kcp01V05NatinsNo1C.setObjectValue( mValueObject.getKcp01V05NatinsNo1C() );
    }

  /**
   * {@inheritDoc}
   */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );

       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }

        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setKcp01V05NatinsNo1A( (String) bindingValue );
        break;
      case 1:
        bindingValue = child.getObjectValue( Integer.class );
        mValueObject.setKcp01V05NatinsNo1B( (Integer) bindingValue );
        break;
      case 2:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setKcp01V05NatinsNo1C( (String) bindingValue );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property " + child.getJaxbName() + " value=" + bindingValue );
      }
    }

  /**
   * {@inheritDoc}
   */
  public Object getObjectValue( final Class<?> type ) throws HostException
    {
    if( type.equals( Kcp01V05NationalInsuranNo1.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName() + " as an incompatible type " + type );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void setObjectValue( final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( Kcp01V05NationalInsuranNo1.class ) )
      {
      mValueObject = (Kcp01V05NationalInsuranNo1) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName() + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /**
   * {@inheritDoc}
   */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public Kcp01V05NationalInsuranNo1 getKcp01V05NationalInsuranNo1()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

