package cascading.legstar.cobolcopybook.beans.bean17.bind;

import java.util.List;

import cascading.legstar.cobolcopybook.beans.bean17.Kcp83V05RewardTierData;
import cascading.legstar.cobolcopybook.beans.bean17.Kcp83V05RewardTiersData;
import cascading.legstar.cobolcopybook.beans.bean17.ObjectFactory;
import com.legstar.coxb.ICobolArrayComplexBinding;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * Kcp83V05RewardTiersData.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class Kcp83V05RewardTiersDataBinding
  extends CComplexBinding
  {

  /** Maximum host bytes size for this complex object. */
  private static final int BYTE_LENGTH = 48;
  /** Static reference to Value object factory to be used as default. */
  private static final ObjectFactory JF = new ObjectFactory();
  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;
  /** Logger. */
  private final Log _log = LogFactory.getLog( getClass() );
  /** Child bound to value object property Kcp83V05RewardTierData(Kcp83V05RewardTierData). */
  public ICobolArrayComplexBinding _kcp83V05RewardTierDataWrapper;
  /** Binding item for complex array binding Kcp83V05RewardTierData. */
  public ICobolComplexBinding _kcp83V05RewardTierDataWrapperItem;
  /** Value object to which this cobol complex element is bound. */
  private Kcp83V05RewardTiersData mValueObject;
  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public Kcp83V05RewardTiersDataBinding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public Kcp83V05RewardTiersDataBinding(
    final Kcp83V05RewardTiersData valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public Kcp83V05RewardTiersDataBinding(
    final String bindingName,
    final String fieldName,
    final ICobolComplexBinding parentBinding,
    final Kcp83V05RewardTiersData valueObject )
    {

    super( bindingName, fieldName, Kcp83V05RewardTiersData.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /** Creates a binding property for each child. */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _kcp83V05RewardTierDataWrapperItem = new Kcp83V05RewardTierDataBinding( "Kcp83V05RewardTierDataWrapperItem",
      "Kcp83V05RewardTierData", this, null );
    _kcp83V05RewardTierDataWrapper = new Kcp83V05RewardTierDataWrapperBinding( "Kcp83V05RewardTierDataWrapper",
      "Kcp83V05RewardTierData", this, _kcp83V05RewardTierDataWrapperItem );
    _kcp83V05RewardTierDataWrapper.setCobolName( "KCP83V05-REWARD-TIER-DATA" );
    _kcp83V05RewardTierDataWrapper.setByteLength( 48 );
    _kcp83V05RewardTierDataWrapper.setItemByteLength( 8 );
    _kcp83V05RewardTierDataWrapper.setMinOccurs( 6 );
    _kcp83V05RewardTierDataWrapper.setMaxOccurs( 6 );

        /* Add children to children list */
    getChildrenList().add( _kcp83V05RewardTierDataWrapper );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /** {@inheritDoc} */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createKcp83V05RewardTiersData();
    }

  /** {@inheritDoc} */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _kcp83V05RewardTierDataWrapper */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property "
        + "_kcp83V05RewardTierDataWrapper"
        + " value=" + mValueObject.getKcp83V05RewardTierData() );
      }
    _kcp83V05RewardTierDataWrapper.setObjectValue( mValueObject.getKcp83V05RewardTierData() );
    }

  /** {@inheritDoc} */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );

       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }

        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( Kcp83V05RewardTierData.class );
        List<Kcp83V05RewardTierData> listKcp83V05RewardTierDataWrapper = cast( bindingValue );
        mValueObject.getKcp83V05RewardTierData().clear();
        mValueObject.getKcp83V05RewardTierData().addAll( listKcp83V05RewardTierDataWrapper );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property "
        + child.getJaxbName()
        + " value=" + bindingValue );
      }
    }

  /** {@inheritDoc} */
  public Object getObjectValue(
    final Class<?> type ) throws HostException
    {
    if( type.equals( Kcp83V05RewardTiersData.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName()
        + " as an incompatible type " + type );
      }
    }

  /** {@inheritDoc} */
  public void setObjectValue(
    final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( Kcp83V05RewardTiersData.class ) )
      {
      mValueObject = (Kcp83V05RewardTiersData) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName()
        + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /** {@inheritDoc} */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public Kcp83V05RewardTiersData getKcp83V05RewardTiersData()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

