package cascading.legstar.cobolcopybook.beans.kcp16v05.bind;

import java.util.List;

import cascading.legstar.cobolcopybook.beans.kcp16v05.Kcp16V05NotificationTable;
import cascading.legstar.cobolcopybook.beans.kcp16v05.Kcp16V05StatementHistData;
import cascading.legstar.cobolcopybook.beans.kcp16v05.ObjectFactory;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolArrayComplexBinding;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.ICobolZonedDecimalBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * Kcp16V05StatementHistData.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class Kcp16V05StatementHistDataBinding
  extends CComplexBinding
  {

  /** Maximum host bytes size for this complex object. */
  private static final int BYTE_LENGTH = 1582;
  /** Binding factory. */
  private static final ICobolBindingFactory BF
    = CobolBindingFactory.getBindingFactory();
  /** Static reference to Value object factory to be used as default. */
  private static final ObjectFactory JF = new ObjectFactory();
  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;
  /** Logger. */
  private final Log _log = LogFactory.getLog( getClass() );
  /** Child bound to value object property Kcp16V05NoOfNotifications(Integer). */
  public ICobolZonedDecimalBinding _kcp16V05NoOfNotifications;
  /** Child bound to value object property Kcp16V05NotificationTable(Kcp16V05NotificationTable). */
  public ICobolArrayComplexBinding _kcp16V05NotificationTableWrapper;
  /** Binding item for complex array binding Kcp16V05NotificationTable. */
  public ICobolComplexBinding _kcp16V05NotificationTableWrapperItem;
  /** Value object to which this cobol complex element is bound. */
  private Kcp16V05StatementHistData mValueObject;
  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public Kcp16V05StatementHistDataBinding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public Kcp16V05StatementHistDataBinding(
    final Kcp16V05StatementHistData valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public Kcp16V05StatementHistDataBinding(
    final String bindingName,
    final String fieldName,
    final ICobolComplexBinding parentBinding,
    final Kcp16V05StatementHistData valueObject )
    {

    super( bindingName, fieldName, Kcp16V05StatementHistData.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /** Creates a binding property for each child. */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _kcp16V05NoOfNotifications = BF.createZonedDecimalBinding( "Kcp16V05NoOfNotifications",
      "Kcp16V05NoOfNotifications", Integer.class, this );
    _kcp16V05NoOfNotifications.setCobolName( "KCP16V05-NO-OF-NOTIFICATIONS" );
    _kcp16V05NoOfNotifications.setByteLength( 2 );
    _kcp16V05NoOfNotifications.setTotalDigits( 2 );
    _kcp16V05NoOfNotifications.setIsODOObject( true );
    _kcp16V05NotificationTableWrapperItem = new Kcp16V05NotificationTableBinding( "Kcp16V05NotificationTableWrapperItem",
      "Kcp16V05NotificationTable", this, null );
    _kcp16V05NotificationTableWrapper = new Kcp16V05NotificationTableWrapperBinding( "Kcp16V05NotificationTableWrapper",
      "Kcp16V05NotificationTable", this, _kcp16V05NotificationTableWrapperItem );
    _kcp16V05NotificationTableWrapper.setCobolName( "KCP16V05-NOTIFICATION-TABLE" );
    _kcp16V05NotificationTableWrapper.setByteLength( 1580 );
    _kcp16V05NotificationTableWrapper.setItemByteLength( 158 );
    _kcp16V05NotificationTableWrapper.setMaxOccurs( 10 );
    _kcp16V05NotificationTableWrapper.setDependingOn( "KCP16V05-NO-OF-NOTIFICATIONS" );

        /* Add children to children list */
    getChildrenList().add( _kcp16V05NoOfNotifications );
    getChildrenList().add( _kcp16V05NotificationTableWrapper );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /** {@inheritDoc} */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createKcp16V05StatementHistData();
    }

  /** {@inheritDoc} */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _kcp16V05NoOfNotifications */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property "
        + "_kcp16V05NoOfNotifications"
        + " value=" + mValueObject.getKcp16V05NoOfNotifications() );
      }
    _kcp16V05NoOfNotifications.setObjectValue( mValueObject.getKcp16V05NoOfNotifications() );
        /* Get Value object property _kcp16V05NotificationTableWrapper */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property "
        + "_kcp16V05NotificationTableWrapper"
        + " value=" + mValueObject.getKcp16V05NotificationTable() );
      }
    _kcp16V05NotificationTableWrapper.setObjectValue( mValueObject.getKcp16V05NotificationTable() );
        /* For variable size array or list, we make sure any
         * associated counter is updated */
    setCounterValue( _kcp16V05NotificationTableWrapper.getDependingOn(),
      ( (List<?>) mValueObject.getKcp16V05NotificationTable() ).size() );
    }

  /** {@inheritDoc} */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );

       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }

        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( Integer.class );
        mValueObject.setKcp16V05NoOfNotifications( (Integer) bindingValue );
        break;
      case 1:
        bindingValue = child.getObjectValue( Kcp16V05NotificationTable.class );
        List<Kcp16V05NotificationTable> listKcp16V05NotificationTableWrapper = cast( bindingValue );
        mValueObject.getKcp16V05NotificationTable().clear();
        mValueObject.getKcp16V05NotificationTable().addAll( listKcp16V05NotificationTableWrapper );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property "
        + child.getJaxbName()
        + " value=" + bindingValue );
      }
    }

  /** {@inheritDoc} */
  public Object getObjectValue(
    final Class<?> type ) throws HostException
    {
    if( type.equals( Kcp16V05StatementHistData.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName()
        + " as an incompatible type " + type );
      }
    }

  /** {@inheritDoc} */
  public void setObjectValue(
    final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( Kcp16V05StatementHistData.class ) )
      {
      mValueObject = (Kcp16V05StatementHistData) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName()
        + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /** {@inheritDoc} */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public Kcp16V05StatementHistData getKcp16V05StatementHistData()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

