package cascading.legstar.cobolcopybook.beans.bean20.bind;

import cascading.legstar.cobolcopybook.beans.bean20.Kcp96V05HistoricalTierData;
import cascading.legstar.cobolcopybook.beans.bean20.ObjectFactory;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.ICobolPackedDecimalBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * Kcp96V05HistoricalTierData.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class Kcp96V05HistoricalTierDataBinding extends CComplexBinding
  {

  /**
   * Maximum host bytes size for this complex object.
   */
  private static final int BYTE_LENGTH = 7;
  /**
   * Binding factory.
   */
  private static final ICobolBindingFactory BF = CobolBindingFactory.getBindingFactory();
  /**
   * Static reference to Value object factory to be used as default.
   */
  private static final ObjectFactory JF = new ObjectFactory();
  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;
  /**
   * Logger.
   */
  private final Log _log = LogFactory.getLog( getClass() );
  /**
   * Child bound to value object property Kcp96V05LimitEffectiveDate(String).
   */
  public ICobolStringBinding _kcp96V05LimitEffectiveDate;
  /**
   * Child bound to value object property Kcp96V05TierUpperLimit(Integer).
   */
  public ICobolPackedDecimalBinding _kcp96V05TierUpperLimit;
  /**
   * Value object to which this cobol complex element is bound.
   */
  private Kcp96V05HistoricalTierData mValueObject;
  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public Kcp96V05HistoricalTierDataBinding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public Kcp96V05HistoricalTierDataBinding( final Kcp96V05HistoricalTierData valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public Kcp96V05HistoricalTierDataBinding( final String bindingName, final String fieldName, final ICobolComplexBinding parentBinding, final Kcp96V05HistoricalTierData valueObject )
    {

    super( bindingName, fieldName, Kcp96V05HistoricalTierData.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /**
   * Creates a binding property for each child.
   */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _kcp96V05LimitEffectiveDate = BF.createStringBinding( "Kcp96V05LimitEffectiveDate", "Kcp96V05LimitEffectiveDate", String.class, this );
    _kcp96V05LimitEffectiveDate.setCobolName( "KCP96V05-LIMIT-EFFECTIVE-DATE" );
    _kcp96V05LimitEffectiveDate.setByteLength( 2 );
    _kcp96V05TierUpperLimit = BF.createPackedDecimalBinding( "Kcp96V05TierUpperLimit", "Kcp96V05TierUpperLimit", Integer.class, this );
    _kcp96V05TierUpperLimit.setCobolName( "KCP96V05-TIER-UPPER-LIMIT" );
    _kcp96V05TierUpperLimit.setByteLength( 5 );
    _kcp96V05TierUpperLimit.setTotalDigits( 9 );
    _kcp96V05TierUpperLimit.setIsSigned( true );

        /* Add children to children list */
    getChildrenList().add( _kcp96V05LimitEffectiveDate );
    getChildrenList().add( _kcp96V05TierUpperLimit );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createKcp96V05HistoricalTierData();
    }

  /**
   * {@inheritDoc}
   */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _kcp96V05LimitEffectiveDate */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp96V05LimitEffectiveDate" + " value=" + mValueObject.getKcp96V05LimitEffectiveDate() );
      }
    _kcp96V05LimitEffectiveDate.setObjectValue( mValueObject.getKcp96V05LimitEffectiveDate() );
        /* Get Value object property _kcp96V05TierUpperLimit */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp96V05TierUpperLimit" + " value=" + mValueObject.getKcp96V05TierUpperLimit() );
      }
    _kcp96V05TierUpperLimit.setObjectValue( mValueObject.getKcp96V05TierUpperLimit() );
    }

  /**
   * {@inheritDoc}
   */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );

       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }

        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setKcp96V05LimitEffectiveDate( (String) bindingValue );
        break;
      case 1:
        bindingValue = child.getObjectValue( Integer.class );
        mValueObject.setKcp96V05TierUpperLimit( (Integer) bindingValue );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property " + child.getJaxbName() + " value=" + bindingValue );
      }
    }

  /**
   * {@inheritDoc}
   */
  public Object getObjectValue( final Class<?> type ) throws HostException
    {
    if( type.equals( Kcp96V05HistoricalTierData.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName() + " as an incompatible type " + type );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void setObjectValue( final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( Kcp96V05HistoricalTierData.class ) )
      {
      mValueObject = (Kcp96V05HistoricalTierData) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName() + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /**
   * {@inheritDoc}
   */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public Kcp96V05HistoricalTierData getKcp96V05HistoricalTierData()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

