package cascading.legstar.cobolcopybook.beans.bean13.bind;

import cascading.legstar.cobolcopybook.beans.bean13.Kcp13V05PrenotPrintDates;
import cascading.legstar.cobolcopybook.beans.bean13.ObjectFactory;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * Kcp13V05PrenotPrintDates.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class Kcp13V05PrenotPrintDatesBinding extends CComplexBinding
  {

  /**
   * Maximum host bytes size for this complex object.
   */
  private static final int BYTE_LENGTH = 3;
  /**
   * Binding factory.
   */
  private static final ICobolBindingFactory BF = CobolBindingFactory.getBindingFactory();
  /**
   * Static reference to Value object factory to be used as default.
   */
  private static final ObjectFactory JF = new ObjectFactory();
  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;
  /**
   * Logger.
   */
  private final Log _log = LogFactory.getLog( getClass() );
  /**
   * Child bound to value object property Kcp13V05PrenotPrintType(String).
   */
  public ICobolStringBinding _kcp13V05PrenotPrintType;
  /**
   * Child bound to value object property Kcp13V05PrenotPrintDate(String).
   */
  public ICobolStringBinding _kcp13V05PrenotPrintDate;
  /**
   * Value object to which this cobol complex element is bound.
   */
  private Kcp13V05PrenotPrintDates mValueObject;
  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public Kcp13V05PrenotPrintDatesBinding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public Kcp13V05PrenotPrintDatesBinding( final Kcp13V05PrenotPrintDates valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public Kcp13V05PrenotPrintDatesBinding( final String bindingName, final String fieldName, final ICobolComplexBinding parentBinding, final Kcp13V05PrenotPrintDates valueObject )
    {

    super( bindingName, fieldName, Kcp13V05PrenotPrintDates.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /**
   * Creates a binding property for each child.
   */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _kcp13V05PrenotPrintType = BF.createStringBinding( "Kcp13V05PrenotPrintType", "Kcp13V05PrenotPrintType", String.class, this );
    _kcp13V05PrenotPrintType.setCobolName( "KCP13V05-PRENOT-PRINT-TYPE" );
    _kcp13V05PrenotPrintType.setByteLength( 1 );
    _kcp13V05PrenotPrintDate = BF.createStringBinding( "Kcp13V05PrenotPrintDate", "Kcp13V05PrenotPrintDate", String.class, this );
    _kcp13V05PrenotPrintDate.setCobolName( "KCP13V05-PRENOT-PRINT-DATE" );
    _kcp13V05PrenotPrintDate.setByteLength( 2 );

        /* Add children to children list */
    getChildrenList().add( _kcp13V05PrenotPrintType );
    getChildrenList().add( _kcp13V05PrenotPrintDate );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createKcp13V05PrenotPrintDates();
    }

  /**
   * {@inheritDoc}
   */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _kcp13V05PrenotPrintType */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp13V05PrenotPrintType" + " value=" + mValueObject.getKcp13V05PrenotPrintType() );
      }
    _kcp13V05PrenotPrintType.setObjectValue( mValueObject.getKcp13V05PrenotPrintType() );
        /* Get Value object property _kcp13V05PrenotPrintDate */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_kcp13V05PrenotPrintDate" + " value=" + mValueObject.getKcp13V05PrenotPrintDate() );
      }
    _kcp13V05PrenotPrintDate.setObjectValue( mValueObject.getKcp13V05PrenotPrintDate() );
    }

  /**
   * {@inheritDoc}
   */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );

       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }

        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setKcp13V05PrenotPrintType( (String) bindingValue );
        break;
      case 1:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setKcp13V05PrenotPrintDate( (String) bindingValue );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property " + child.getJaxbName() + " value=" + bindingValue );
      }
    }

  /**
   * {@inheritDoc}
   */
  public Object getObjectValue( final Class<?> type ) throws HostException
    {
    if( type.equals( Kcp13V05PrenotPrintDates.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName() + " as an incompatible type " + type );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void setObjectValue( final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( Kcp13V05PrenotPrintDates.class ) )
      {
      mValueObject = (Kcp13V05PrenotPrintDates) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName() + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /**
   * {@inheritDoc}
   */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public Kcp13V05PrenotPrintDates getKcp13V05PrenotPrintDates()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

