package cascading.hadoop.legstar.cobol.beans.custdat.bind;

import cascading.hadoop.legstar.cobol.beans.custdat.ObjectFactory;
import cascading.hadoop.legstar.cobol.beans.custdat.TransactionDate;
import com.legstar.coxb.CobolBindingFactory;
import com.legstar.coxb.ICobolBinding;
import com.legstar.coxb.ICobolBindingFactory;
import com.legstar.coxb.ICobolComplexBinding;
import com.legstar.coxb.ICobolStringBinding;
import com.legstar.coxb.common.CComplexBinding;
import com.legstar.coxb.host.HostException;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * LegStar Binding for Complex element :
 * TransactionDate.
 * <p/>
 * This class was generated by LegStar Binding generator.
 */
public class TransactionDateBinding extends CComplexBinding
  {

  /**
   * Value object to which this cobol complex element is bound.
   */
  private TransactionDate mValueObject;

  /**
   * Indicates that the associated Value object just came from the constructor
   * and doesn't need to be recreated.
   */
  private boolean mUnusedValueObject = false;

  /**
   * Maximum host bytes size for this complex object.
   */
  private static final int BYTE_LENGTH = 8;

  /**
   * Child bound to value object property TransactionDay(String).
   */
  public ICobolStringBinding _transactionDay;
  /**
   * Child bound to value object property Filler13(String).
   */
  public ICobolStringBinding _filler13;
  /**
   * Child bound to value object property TransactionMonth(String).
   */
  public ICobolStringBinding _transactionMonth;
  /**
   * Child bound to value object property Filler15(String).
   */
  public ICobolStringBinding _filler15;
  /**
   * Child bound to value object property TransactionYear(String).
   */
  public ICobolStringBinding _transactionYear;

  /**
   * Logger.
   */
  private final Log _log = LogFactory.getLog( getClass() );

  /**
   * Binding factory.
   */
  private static final ICobolBindingFactory BF = CobolBindingFactory.getBindingFactory();

  /**
   * Static reference to Value object factory to be used as default.
   */
  private static final ObjectFactory JF = new ObjectFactory();

  /**
   * Current Value object factory (Defaults to the static one but can be
   * changed).
   */
  private ObjectFactory mValueObjectFactory = JF;

  /**
   * Constructor for a root Complex element without a bound Value object.
   */
  public TransactionDateBinding()
    {
    this( null );
    }

  /**
   * Constructor for a root Complex element with a bound Value object.
   *
   * @param valueObject the concrete Value object instance bound to this
   *                    complex element
   */
  public TransactionDateBinding( final TransactionDate valueObject )
    {
    this( "", "", null, valueObject );
    }

  /**
   * Constructor for a Complex element as a child of another element and
   * an associated Value object.
   *
   * @param bindingName   the identifier for this binding
   * @param fieldName     field name in parent Value object
   * @param valueObject   the concrete Value object instance bound to this
   *                      complex element
   * @param parentBinding a reference to the parent binding
   */
  public TransactionDateBinding( final String bindingName, final String fieldName, final ICobolComplexBinding parentBinding, final TransactionDate valueObject )
    {

    super( bindingName, fieldName, TransactionDate.class, null, parentBinding );
    mValueObject = valueObject;
    if( mValueObject != null )
      {
      mUnusedValueObject = true;
      }
    initChildren();
    setByteLength( BYTE_LENGTH );
    }

  /**
   * Creates a binding property for each child.
   */
  private void initChildren()
    {
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing started" );
      }
        /* Create binding children instances */

    _transactionDay = BF.createStringBinding( "TransactionDay", "TransactionDay", String.class, this );
    _transactionDay.setCobolName( "TRANSACTION-DAY" );
    _transactionDay.setByteLength( 2 );
    _filler13 = BF.createStringBinding( "Filler13", "Filler13", String.class, this );
    _filler13.setCobolName( "FILLER" );
    _filler13.setByteLength( 1 );
    _transactionMonth = BF.createStringBinding( "TransactionMonth", "TransactionMonth", String.class, this );
    _transactionMonth.setCobolName( "TRANSACTION-MONTH" );
    _transactionMonth.setByteLength( 2 );
    _filler15 = BF.createStringBinding( "Filler15", "Filler15", String.class, this );
    _filler15.setCobolName( "FILLER" );
    _filler15.setByteLength( 1 );
    _transactionYear = BF.createStringBinding( "TransactionYear", "TransactionYear", String.class, this );
    _transactionYear.setCobolName( "TRANSACTION-YEAR" );
    _transactionYear.setByteLength( 2 );

        /* Add children to children list */
    getChildrenList().add( _transactionDay );
    getChildrenList().add( _filler13 );
    getChildrenList().add( _transactionMonth );
    getChildrenList().add( _filler15 );
    getChildrenList().add( _transactionYear );

    if( _log.isDebugEnabled() )
      {
      _log.debug( "Initializing successful" );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void createValueObject() throws HostException
    {
        /* Since this complex binding has a constructor that takes a
         * Value object, we might already have a Value object that
         * was not used yet. */
    if( mUnusedValueObject && mValueObject != null )
      {
      mUnusedValueObject = false;
      return;
      }
    mValueObject = mValueObjectFactory.createTransactionDate();
    }

  /**
   * {@inheritDoc}
   */
  public void setChildrenValues() throws HostException
    {

         /* Make sure there is an associated Value object*/
    if( mValueObject == null )
      {
      createValueObject();
      }
        /* Get Value object property _transactionDay */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_transactionDay" + " value=" + mValueObject.getTransactionDay() );
      }
    _transactionDay.setObjectValue( mValueObject.getTransactionDay() );
        /* Get Value object property _filler13 */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_filler13" + " value=" + mValueObject.getFiller13() );
      }
    _filler13.setObjectValue( mValueObject.getFiller13() );
        /* Get Value object property _transactionMonth */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_transactionMonth" + " value=" + mValueObject.getTransactionMonth() );
      }
    _transactionMonth.setObjectValue( mValueObject.getTransactionMonth() );
        /* Get Value object property _filler15 */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_filler15" + " value=" + mValueObject.getFiller15() );
      }
    _filler15.setObjectValue( mValueObject.getFiller15() );
        /* Get Value object property _transactionYear */
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Getting value from Value object property " + "_transactionYear" + " value=" + mValueObject.getTransactionYear() );
      }
    _transactionYear.setObjectValue( mValueObject.getTransactionYear() );
    }

  /**
   * {@inheritDoc}
   */
  public void setPropertyValue( final int index ) throws HostException
    {

    ICobolBinding child = getChildrenList().get( index );
        
       /* Children that are not bound to a value object are ignored.
        * This includes Choices and dynamically generated counters
        * for instance.  */
    if( !child.isBound() )
      {
      return;
      }
        
        /* Set the Value object property value from binding object */
    Object bindingValue = null;
    switch( index )
      {
      case 0:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setTransactionDay( (String) bindingValue );
        break;
      case 1:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setFiller13( (String) bindingValue );
        break;
      case 2:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setTransactionMonth( (String) bindingValue );
        break;
      case 3:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setFiller15( (String) bindingValue );
        break;
      case 4:
        bindingValue = child.getObjectValue( String.class );
        mValueObject.setTransactionYear( (String) bindingValue );
        break;
      default:
        break;
      }
    if( _log.isDebugEnabled() )
      {
      _log.debug( "Setting value of Value object property " + child.getJaxbName() + " value=" + bindingValue );
      }
    }

  /**
   * {@inheritDoc}
   */
  public Object getObjectValue( final Class<?> type ) throws HostException
    {
    if( type.equals( TransactionDate.class ) )
      {
      return mValueObject;
      }
    else
      {
      throw new HostException( "Attempt to get binding " + getBindingName() + " as an incompatible type " + type );
      }
    }

  /**
   * {@inheritDoc}
   */
  public void setObjectValue( final Object bindingValue ) throws HostException
    {
    if( bindingValue == null )
      {
      mValueObject = null;
      return;
      }
    if( bindingValue.getClass().equals( TransactionDate.class ) )
      {
      mValueObject = (TransactionDate) bindingValue;
      }
    else
      {
      throw new HostException( "Attempt to set binding " + getBindingName() + " from an incompatible value " + bindingValue );
      }
    }

  /**
   * @return the java object factory for objects creation
   */
  public ObjectFactory getObjectFactory()
    {
    return mValueObjectFactory;
    }

  /**
   * @param valueObjectFactory the java object factory for objects creation
   */
  public void setObjectFactory( final Object valueObjectFactory )
    {
    mValueObjectFactory = (ObjectFactory) valueObjectFactory;
    }

  /**
   * {@inheritDoc}
   */
  public boolean isSet()
    {
    return ( mValueObject != null );
    }

  /**
   * @return the bound Value object
   */
  public TransactionDate getTransactionDate()
    {
    return mValueObject;
    }

  /**
   * The COBOL complex element maximum length in bytes.
   *
   * @return COBOL complex element maximum length in bytes
   */
  public int getByteLength()
    {
    return BYTE_LENGTH;
    }
  }

