package cascading.legstar.cobolcopybook.fields;

import java.lang.reflect.Type;

import cascading.tuple.Fields;

public class Field21 extends Fields
  {

  private static final long serialVersionUID = -1L;

  public Field21()
    {
    super(
      new Comparable[]{
        "Kcp97V05NoOfTiers"
        , "Kcp97V05RateTierNumber_0"
        , "Kcp97V05XsRateChangeInd_0"
        , "Kcp97V05NoOfChanges_0"
        , "Kcp97V05RateEffectiveDate_0_0"
        , "Kcp97V05EffectiveRate_0_0"
        , "Kcp97V05RateCode_0_0"
        , "Kcp97V05DefaultRateCode_0_0"
        , "Kcp97V05MinimumRate_0_0"
        , "Kcp97V05RateLink_0_0"
        , "Kcp97V05RateConsistencyInd_0_0"
        , "Kcp97V05RateName_0_0"
        , "Kcp97V05ZeroRateCode_0_0"
        , "Kcp97V05DrintType_0_0"
        , "Kcp97V05RateEffectiveDate_0_1"
        , "Kcp97V05EffectiveRate_0_1"
        , "Kcp97V05RateCode_0_1"
        , "Kcp97V05DefaultRateCode_0_1"
        , "Kcp97V05MinimumRate_0_1"
        , "Kcp97V05RateLink_0_1"
        , "Kcp97V05RateConsistencyInd_0_1"
        , "Kcp97V05RateName_0_1"
        , "Kcp97V05ZeroRateCode_0_1"
        , "Kcp97V05DrintType_0_1"
        , "Kcp97V05RateEffectiveDate_0_2"
        , "Kcp97V05EffectiveRate_0_2"
        , "Kcp97V05RateCode_0_2"
        , "Kcp97V05DefaultRateCode_0_2"
        , "Kcp97V05MinimumRate_0_2"
        , "Kcp97V05RateLink_0_2"
        , "Kcp97V05RateConsistencyInd_0_2"
        , "Kcp97V05RateName_0_2"
        , "Kcp97V05ZeroRateCode_0_2"
        , "Kcp97V05DrintType_0_2"
        , "Kcp97V05RateEffectiveDate_0_3"
        , "Kcp97V05EffectiveRate_0_3"
        , "Kcp97V05RateCode_0_3"
        , "Kcp97V05DefaultRateCode_0_3"
        , "Kcp97V05MinimumRate_0_3"
        , "Kcp97V05RateLink_0_3"
        , "Kcp97V05RateConsistencyInd_0_3"
        , "Kcp97V05RateName_0_3"
        , "Kcp97V05ZeroRateCode_0_3"
        , "Kcp97V05DrintType_0_3"
        , "Kcp97V05DefaultRateT006Key_0"
        , "Kcp97V05RateTierNumber_1"
        , "Kcp97V05XsRateChangeInd_1"
        , "Kcp97V05NoOfChanges_1"
        , "Kcp97V05RateEffectiveDate_1_0"
        , "Kcp97V05EffectiveRate_1_0"
        , "Kcp97V05RateCode_1_0"
        , "Kcp97V05DefaultRateCode_1_0"
        , "Kcp97V05MinimumRate_1_0"
        , "Kcp97V05RateLink_1_0"
        , "Kcp97V05RateConsistencyInd_1_0"
        , "Kcp97V05RateName_1_0"
        , "Kcp97V05ZeroRateCode_1_0"
        , "Kcp97V05DrintType_1_0"
        , "Kcp97V05RateEffectiveDate_1_1"
        , "Kcp97V05EffectiveRate_1_1"
        , "Kcp97V05RateCode_1_1"
        , "Kcp97V05DefaultRateCode_1_1"
        , "Kcp97V05MinimumRate_1_1"
        , "Kcp97V05RateLink_1_1"
        , "Kcp97V05RateConsistencyInd_1_1"
        , "Kcp97V05RateName_1_1"
        , "Kcp97V05ZeroRateCode_1_1"
        , "Kcp97V05DrintType_1_1"
        , "Kcp97V05RateEffectiveDate_1_2"
        , "Kcp97V05EffectiveRate_1_2"
        , "Kcp97V05RateCode_1_2"
        , "Kcp97V05DefaultRateCode_1_2"
        , "Kcp97V05MinimumRate_1_2"
        , "Kcp97V05RateLink_1_2"
        , "Kcp97V05RateConsistencyInd_1_2"
        , "Kcp97V05RateName_1_2"
        , "Kcp97V05ZeroRateCode_1_2"
        , "Kcp97V05DrintType_1_2"
        , "Kcp97V05RateEffectiveDate_1_3"
        , "Kcp97V05EffectiveRate_1_3"
        , "Kcp97V05RateCode_1_3"
        , "Kcp97V05DefaultRateCode_1_3"
        , "Kcp97V05MinimumRate_1_3"
        , "Kcp97V05RateLink_1_3"
        , "Kcp97V05RateConsistencyInd_1_3"
        , "Kcp97V05RateName_1_3"
        , "Kcp97V05ZeroRateCode_1_3"
        , "Kcp97V05DrintType_1_3"
        , "Kcp97V05DefaultRateT006Key_1"
        , "Kcp97V05RateTierNumber_2"
        , "Kcp97V05XsRateChangeInd_2"
        , "Kcp97V05NoOfChanges_2"
        , "Kcp97V05RateEffectiveDate_2_0"
        , "Kcp97V05EffectiveRate_2_0"
        , "Kcp97V05RateCode_2_0"
        , "Kcp97V05DefaultRateCode_2_0"
        , "Kcp97V05MinimumRate_2_0"
        , "Kcp97V05RateLink_2_0"
        , "Kcp97V05RateConsistencyInd_2_0"
        , "Kcp97V05RateName_2_0"
        , "Kcp97V05ZeroRateCode_2_0"
        , "Kcp97V05DrintType_2_0"
        , "Kcp97V05RateEffectiveDate_2_1"
        , "Kcp97V05EffectiveRate_2_1"
        , "Kcp97V05RateCode_2_1"
        , "Kcp97V05DefaultRateCode_2_1"
        , "Kcp97V05MinimumRate_2_1"
        , "Kcp97V05RateLink_2_1"
        , "Kcp97V05RateConsistencyInd_2_1"
        , "Kcp97V05RateName_2_1"
        , "Kcp97V05ZeroRateCode_2_1"
        , "Kcp97V05DrintType_2_1"
        , "Kcp97V05RateEffectiveDate_2_2"
        , "Kcp97V05EffectiveRate_2_2"
        , "Kcp97V05RateCode_2_2"
        , "Kcp97V05DefaultRateCode_2_2"
        , "Kcp97V05MinimumRate_2_2"
        , "Kcp97V05RateLink_2_2"
        , "Kcp97V05RateConsistencyInd_2_2"
        , "Kcp97V05RateName_2_2"
        , "Kcp97V05ZeroRateCode_2_2"
        , "Kcp97V05DrintType_2_2"
        , "Kcp97V05RateEffectiveDate_2_3"
        , "Kcp97V05EffectiveRate_2_3"
        , "Kcp97V05RateCode_2_3"
        , "Kcp97V05DefaultRateCode_2_3"
        , "Kcp97V05MinimumRate_2_3"
        , "Kcp97V05RateLink_2_3"
        , "Kcp97V05RateConsistencyInd_2_3"
        , "Kcp97V05RateName_2_3"
        , "Kcp97V05ZeroRateCode_2_3"
        , "Kcp97V05DrintType_2_3"
        , "Kcp97V05DefaultRateT006Key_2"
        , "Kcp97V05RateTierNumber_3"
        , "Kcp97V05XsRateChangeInd_3"
        , "Kcp97V05NoOfChanges_3"
        , "Kcp97V05RateEffectiveDate_3_0"
        , "Kcp97V05EffectiveRate_3_0"
        , "Kcp97V05RateCode_3_0"
        , "Kcp97V05DefaultRateCode_3_0"
        , "Kcp97V05MinimumRate_3_0"
        , "Kcp97V05RateLink_3_0"
        , "Kcp97V05RateConsistencyInd_3_0"
        , "Kcp97V05RateName_3_0"
        , "Kcp97V05ZeroRateCode_3_0"
        , "Kcp97V05DrintType_3_0"
        , "Kcp97V05RateEffectiveDate_3_1"
        , "Kcp97V05EffectiveRate_3_1"
        , "Kcp97V05RateCode_3_1"
        , "Kcp97V05DefaultRateCode_3_1"
        , "Kcp97V05MinimumRate_3_1"
        , "Kcp97V05RateLink_3_1"
        , "Kcp97V05RateConsistencyInd_3_1"
        , "Kcp97V05RateName_3_1"
        , "Kcp97V05ZeroRateCode_3_1"
        , "Kcp97V05DrintType_3_1"
        , "Kcp97V05RateEffectiveDate_3_2"
        , "Kcp97V05EffectiveRate_3_2"
        , "Kcp97V05RateCode_3_2"
        , "Kcp97V05DefaultRateCode_3_2"
        , "Kcp97V05MinimumRate_3_2"
        , "Kcp97V05RateLink_3_2"
        , "Kcp97V05RateConsistencyInd_3_2"
        , "Kcp97V05RateName_3_2"
        , "Kcp97V05ZeroRateCode_3_2"
        , "Kcp97V05DrintType_3_2"
        , "Kcp97V05RateEffectiveDate_3_3"
        , "Kcp97V05EffectiveRate_3_3"
        , "Kcp97V05RateCode_3_3"
        , "Kcp97V05DefaultRateCode_3_3"
        , "Kcp97V05MinimumRate_3_3"
        , "Kcp97V05RateLink_3_3"
        , "Kcp97V05RateConsistencyInd_3_3"
        , "Kcp97V05RateName_3_3"
        , "Kcp97V05ZeroRateCode_3_3"
        , "Kcp97V05DrintType_3_3"
        , "Kcp97V05DefaultRateT006Key_3"
      }, new Type[]{
        short.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
      }
    );
    }

  }
