package cascading.legstar.cobolcopybook.fields;

import java.lang.reflect.Type;

import cascading.tuple.Fields;

public class Kcp94v05 extends Fields
  {

  private static final long serialVersionUID = -1L;

  public Kcp94v05()
    {
    super(
      new Comparable[]{
        "Kcp94V05NoOfTiers1"
        , "Kcp94V05RateTierNumber_0"
        , "Kcp94V05XsRateChangeInd_0"
        , "Kcp94V05NoOfChanges_0"
        , "Kcp94V05RateEffectiveDate_0_0"
        , "Kcp94V05EffectiveRate_0_0"
        , "Kcp94V05RateCode_0_0"
        , "Kcp94V05DefaultRateCode_0_0"
        , "Kcp94V05MinimumRate_0_0"
        , "Kcp94V05RateLink_0_0"
        , "Kcp94V05RateConsistencyInd_0_0"
        , "Kcp94V05RateName_0_0"
        , "Kcp94V05ZeroRateCode_0_0"
        , "Kcp94V05CrintType_0_0"
        , "Kcp94V05RateEffectiveDate_0_1"
        , "Kcp94V05EffectiveRate_0_1"
        , "Kcp94V05RateCode_0_1"
        , "Kcp94V05DefaultRateCode_0_1"
        , "Kcp94V05MinimumRate_0_1"
        , "Kcp94V05RateLink_0_1"
        , "Kcp94V05RateConsistencyInd_0_1"
        , "Kcp94V05RateName_0_1"
        , "Kcp94V05ZeroRateCode_0_1"
        , "Kcp94V05CrintType_0_1"
        , "Kcp94V05RateEffectiveDate_0_2"
        , "Kcp94V05EffectiveRate_0_2"
        , "Kcp94V05RateCode_0_2"
        , "Kcp94V05DefaultRateCode_0_2"
        , "Kcp94V05MinimumRate_0_2"
        , "Kcp94V05RateLink_0_2"
        , "Kcp94V05RateConsistencyInd_0_2"
        , "Kcp94V05RateName_0_2"
        , "Kcp94V05ZeroRateCode_0_2"
        , "Kcp94V05CrintType_0_2"
        , "Kcp94V05RateEffectiveDate_0_3"
        , "Kcp94V05EffectiveRate_0_3"
        , "Kcp94V05RateCode_0_3"
        , "Kcp94V05DefaultRateCode_0_3"
        , "Kcp94V05MinimumRate_0_3"
        , "Kcp94V05RateLink_0_3"
        , "Kcp94V05RateConsistencyInd_0_3"
        , "Kcp94V05RateName_0_3"
        , "Kcp94V05ZeroRateCode_0_3"
        , "Kcp94V05CrintType_0_3"
        , "Kcp94V05DefaultRateT006Key_0"
        , "Kcp94V05RateTierNumber_1"
        , "Kcp94V05XsRateChangeInd_1"
        , "Kcp94V05NoOfChanges_1"
        , "Kcp94V05RateEffectiveDate_1_0"
        , "Kcp94V05EffectiveRate_1_0"
        , "Kcp94V05RateCode_1_0"
        , "Kcp94V05DefaultRateCode_1_0"
        , "Kcp94V05MinimumRate_1_0"
        , "Kcp94V05RateLink_1_0"
        , "Kcp94V05RateConsistencyInd_1_0"
        , "Kcp94V05RateName_1_0"
        , "Kcp94V05ZeroRateCode_1_0"
        , "Kcp94V05CrintType_1_0"
        , "Kcp94V05RateEffectiveDate_1_1"
        , "Kcp94V05EffectiveRate_1_1"
        , "Kcp94V05RateCode_1_1"
        , "Kcp94V05DefaultRateCode_1_1"
        , "Kcp94V05MinimumRate_1_1"
        , "Kcp94V05RateLink_1_1"
        , "Kcp94V05RateConsistencyInd_1_1"
        , "Kcp94V05RateName_1_1"
        , "Kcp94V05ZeroRateCode_1_1"
        , "Kcp94V05CrintType_1_1"
        , "Kcp94V05RateEffectiveDate_1_2"
        , "Kcp94V05EffectiveRate_1_2"
        , "Kcp94V05RateCode_1_2"
        , "Kcp94V05DefaultRateCode_1_2"
        , "Kcp94V05MinimumRate_1_2"
        , "Kcp94V05RateLink_1_2"
        , "Kcp94V05RateConsistencyInd_1_2"
        , "Kcp94V05RateName_1_2"
        , "Kcp94V05ZeroRateCode_1_2"
        , "Kcp94V05CrintType_1_2"
        , "Kcp94V05RateEffectiveDate_1_3"
        , "Kcp94V05EffectiveRate_1_3"
        , "Kcp94V05RateCode_1_3"
        , "Kcp94V05DefaultRateCode_1_3"
        , "Kcp94V05MinimumRate_1_3"
        , "Kcp94V05RateLink_1_3"
        , "Kcp94V05RateConsistencyInd_1_3"
        , "Kcp94V05RateName_1_3"
        , "Kcp94V05ZeroRateCode_1_3"
        , "Kcp94V05CrintType_1_3"
        , "Kcp94V05DefaultRateT006Key_1"
        , "Kcp94V05RateTierNumber_2"
        , "Kcp94V05XsRateChangeInd_2"
        , "Kcp94V05NoOfChanges_2"
        , "Kcp94V05RateEffectiveDate_2_0"
        , "Kcp94V05EffectiveRate_2_0"
        , "Kcp94V05RateCode_2_0"
        , "Kcp94V05DefaultRateCode_2_0"
        , "Kcp94V05MinimumRate_2_0"
        , "Kcp94V05RateLink_2_0"
        , "Kcp94V05RateConsistencyInd_2_0"
        , "Kcp94V05RateName_2_0"
        , "Kcp94V05ZeroRateCode_2_0"
        , "Kcp94V05CrintType_2_0"
        , "Kcp94V05RateEffectiveDate_2_1"
        , "Kcp94V05EffectiveRate_2_1"
        , "Kcp94V05RateCode_2_1"
        , "Kcp94V05DefaultRateCode_2_1"
        , "Kcp94V05MinimumRate_2_1"
        , "Kcp94V05RateLink_2_1"
        , "Kcp94V05RateConsistencyInd_2_1"
        , "Kcp94V05RateName_2_1"
        , "Kcp94V05ZeroRateCode_2_1"
        , "Kcp94V05CrintType_2_1"
        , "Kcp94V05RateEffectiveDate_2_2"
        , "Kcp94V05EffectiveRate_2_2"
        , "Kcp94V05RateCode_2_2"
        , "Kcp94V05DefaultRateCode_2_2"
        , "Kcp94V05MinimumRate_2_2"
        , "Kcp94V05RateLink_2_2"
        , "Kcp94V05RateConsistencyInd_2_2"
        , "Kcp94V05RateName_2_2"
        , "Kcp94V05ZeroRateCode_2_2"
        , "Kcp94V05CrintType_2_2"
        , "Kcp94V05RateEffectiveDate_2_3"
        , "Kcp94V05EffectiveRate_2_3"
        , "Kcp94V05RateCode_2_3"
        , "Kcp94V05DefaultRateCode_2_3"
        , "Kcp94V05MinimumRate_2_3"
        , "Kcp94V05RateLink_2_3"
        , "Kcp94V05RateConsistencyInd_2_3"
        , "Kcp94V05RateName_2_3"
        , "Kcp94V05ZeroRateCode_2_3"
        , "Kcp94V05CrintType_2_3"
        , "Kcp94V05DefaultRateT006Key_2"
        , "Kcp94V05RateTierNumber_3"
        , "Kcp94V05XsRateChangeInd_3"
        , "Kcp94V05NoOfChanges_3"
        , "Kcp94V05RateEffectiveDate_3_0"
        , "Kcp94V05EffectiveRate_3_0"
        , "Kcp94V05RateCode_3_0"
        , "Kcp94V05DefaultRateCode_3_0"
        , "Kcp94V05MinimumRate_3_0"
        , "Kcp94V05RateLink_3_0"
        , "Kcp94V05RateConsistencyInd_3_0"
        , "Kcp94V05RateName_3_0"
        , "Kcp94V05ZeroRateCode_3_0"
        , "Kcp94V05CrintType_3_0"
        , "Kcp94V05RateEffectiveDate_3_1"
        , "Kcp94V05EffectiveRate_3_1"
        , "Kcp94V05RateCode_3_1"
        , "Kcp94V05DefaultRateCode_3_1"
        , "Kcp94V05MinimumRate_3_1"
        , "Kcp94V05RateLink_3_1"
        , "Kcp94V05RateConsistencyInd_3_1"
        , "Kcp94V05RateName_3_1"
        , "Kcp94V05ZeroRateCode_3_1"
        , "Kcp94V05CrintType_3_1"
        , "Kcp94V05RateEffectiveDate_3_2"
        , "Kcp94V05EffectiveRate_3_2"
        , "Kcp94V05RateCode_3_2"
        , "Kcp94V05DefaultRateCode_3_2"
        , "Kcp94V05MinimumRate_3_2"
        , "Kcp94V05RateLink_3_2"
        , "Kcp94V05RateConsistencyInd_3_2"
        , "Kcp94V05RateName_3_2"
        , "Kcp94V05ZeroRateCode_3_2"
        , "Kcp94V05CrintType_3_2"
        , "Kcp94V05RateEffectiveDate_3_3"
        , "Kcp94V05EffectiveRate_3_3"
        , "Kcp94V05RateCode_3_3"
        , "Kcp94V05DefaultRateCode_3_3"
        , "Kcp94V05MinimumRate_3_3"
        , "Kcp94V05RateLink_3_3"
        , "Kcp94V05RateConsistencyInd_3_3"
        , "Kcp94V05RateName_3_3"
        , "Kcp94V05ZeroRateCode_3_3"
        , "Kcp94V05CrintType_3_3"
        , "Kcp94V05DefaultRateT006Key_3"
        , "Kcp94V05RateTierNumber_4"
        , "Kcp94V05XsRateChangeInd_4"
        , "Kcp94V05NoOfChanges_4"
        , "Kcp94V05RateEffectiveDate_4_0"
        , "Kcp94V05EffectiveRate_4_0"
        , "Kcp94V05RateCode_4_0"
        , "Kcp94V05DefaultRateCode_4_0"
        , "Kcp94V05MinimumRate_4_0"
        , "Kcp94V05RateLink_4_0"
        , "Kcp94V05RateConsistencyInd_4_0"
        , "Kcp94V05RateName_4_0"
        , "Kcp94V05ZeroRateCode_4_0"
        , "Kcp94V05CrintType_4_0"
        , "Kcp94V05RateEffectiveDate_4_1"
        , "Kcp94V05EffectiveRate_4_1"
        , "Kcp94V05RateCode_4_1"
        , "Kcp94V05DefaultRateCode_4_1"
        , "Kcp94V05MinimumRate_4_1"
        , "Kcp94V05RateLink_4_1"
        , "Kcp94V05RateConsistencyInd_4_1"
        , "Kcp94V05RateName_4_1"
        , "Kcp94V05ZeroRateCode_4_1"
        , "Kcp94V05CrintType_4_1"
        , "Kcp94V05RateEffectiveDate_4_2"
        , "Kcp94V05EffectiveRate_4_2"
        , "Kcp94V05RateCode_4_2"
        , "Kcp94V05DefaultRateCode_4_2"
        , "Kcp94V05MinimumRate_4_2"
        , "Kcp94V05RateLink_4_2"
        , "Kcp94V05RateConsistencyInd_4_2"
        , "Kcp94V05RateName_4_2"
        , "Kcp94V05ZeroRateCode_4_2"
        , "Kcp94V05CrintType_4_2"
        , "Kcp94V05RateEffectiveDate_4_3"
        , "Kcp94V05EffectiveRate_4_3"
        , "Kcp94V05RateCode_4_3"
        , "Kcp94V05DefaultRateCode_4_3"
        , "Kcp94V05MinimumRate_4_3"
        , "Kcp94V05RateLink_4_3"
        , "Kcp94V05RateConsistencyInd_4_3"
        , "Kcp94V05RateName_4_3"
        , "Kcp94V05ZeroRateCode_4_3"
        , "Kcp94V05CrintType_4_3"
        , "Kcp94V05DefaultRateT006Key_4"
        , "Kcp94V05RateTierNumber_5"
        , "Kcp94V05XsRateChangeInd_5"
        , "Kcp94V05NoOfChanges_5"
        , "Kcp94V05RateEffectiveDate_5_0"
        , "Kcp94V05EffectiveRate_5_0"
        , "Kcp94V05RateCode_5_0"
        , "Kcp94V05DefaultRateCode_5_0"
        , "Kcp94V05MinimumRate_5_0"
        , "Kcp94V05RateLink_5_0"
        , "Kcp94V05RateConsistencyInd_5_0"
        , "Kcp94V05RateName_5_0"
        , "Kcp94V05ZeroRateCode_5_0"
        , "Kcp94V05CrintType_5_0"
        , "Kcp94V05RateEffectiveDate_5_1"
        , "Kcp94V05EffectiveRate_5_1"
        , "Kcp94V05RateCode_5_1"
        , "Kcp94V05DefaultRateCode_5_1"
        , "Kcp94V05MinimumRate_5_1"
        , "Kcp94V05RateLink_5_1"
        , "Kcp94V05RateConsistencyInd_5_1"
        , "Kcp94V05RateName_5_1"
        , "Kcp94V05ZeroRateCode_5_1"
        , "Kcp94V05CrintType_5_1"
        , "Kcp94V05RateEffectiveDate_5_2"
        , "Kcp94V05EffectiveRate_5_2"
        , "Kcp94V05RateCode_5_2"
        , "Kcp94V05DefaultRateCode_5_2"
        , "Kcp94V05MinimumRate_5_2"
        , "Kcp94V05RateLink_5_2"
        , "Kcp94V05RateConsistencyInd_5_2"
        , "Kcp94V05RateName_5_2"
        , "Kcp94V05ZeroRateCode_5_2"
        , "Kcp94V05CrintType_5_2"
        , "Kcp94V05RateEffectiveDate_5_3"
        , "Kcp94V05EffectiveRate_5_3"
        , "Kcp94V05RateCode_5_3"
        , "Kcp94V05DefaultRateCode_5_3"
        , "Kcp94V05MinimumRate_5_3"
        , "Kcp94V05RateLink_5_3"
        , "Kcp94V05RateConsistencyInd_5_3"
        , "Kcp94V05RateName_5_3"
        , "Kcp94V05ZeroRateCode_5_3"
        , "Kcp94V05CrintType_5_3"
        , "Kcp94V05DefaultRateT006Key_5"
      }, new Type[]{
        short.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.math.BigDecimal.class
        , java.math.BigDecimal.class
        , java.lang.String.class
        , java.lang.String.class
        , java.lang.String.class
        , short.class
        , java.lang.String.class
      }
    );
    }

  }
